export const POPUP_COPY = {
  'app.title': 'EmeraldPix',
  'errors.unknownError': 'Something went wrong. Try again.',
  'formats.jpg': 'JPG',
  'formats.pdf': 'PDF',
  'formats.png': 'PNG',
  'popup.actions.capture': 'Page',
  'popup.actions.captureArea': 'Area',
  'popup.actions.capturing': 'Capturing...',
  'popup.actions.closeSettings': 'Close settings',
  'popup.actions.openDownloads': 'Open downloads',
  'popup.actions.openSettings': 'Open settings',
  'popup.actions.resetSettings': 'Reset to defaults',
  'popup.actions.retry': 'Try again',
  'popup.actions.toggleThemeDark': 'Switch to dark mode',
  'popup.actions.toggleThemeLight': 'Switch to light mode',
  'popup.alerts.largePage': '{count} {fileWord}.',
  'popup.alerts.statusUnavailable': 'Status unavailable.',
  'popup.errors.couldNotStart': 'Could not start capture.',
  'popup.errors.invalidStartStatus': 'Capture did not return a valid status.',
  'popup.misc.appVersion': 'v{version}',
  'popup.modal.confirmReset': 'Reset all settings to their defaults?',
  'popup.modal.disabled': 'Off',
  'popup.modal.enabled': 'On',
  'popup.modal.themeDark': 'Dark',
  'popup.modal.themeHelp': 'Pick a manual theme or return to your system preference.',
  'popup.modal.themeLight': 'Light',
  'popup.modal.themeSystem': 'System',
  'popup.modal.title': 'Settings',
  'popup.quick.format': 'Format',
  'popup.settings.appearance': 'Appearance',
  'popup.settings.askWhereToSave': 'Force save dialog',
  'popup.settings.askWhereToSaveHelp':
    "Force the browser save dialog before each capture. If this is off, your browser may still ask when its own 'Ask where to save each file' setting is enabled.",
  'popup.settings.capture': 'Capture',
  'popup.settings.jpgQuality': 'JPG quality',
  'popup.settings.jpgQualityHelp': 'Controls compression for JPG exports.',
  'popup.settings.saving': 'Saving',
  'popup.settings.smoothStitching': 'Improve long-page stitching',
  'popup.settings.smoothStitchingHelp':
    'Reduces visible seams on difficult long pages. Leave it off unless a page stitches badly.',
  'popup.status.analyzingPage': 'Analyzing the page...',
  'popup.status.captureComplete': 'Saved',
  'popup.status.captureFailed': 'Try again',
  'popup.status.capturingPage': 'Capturing the page...',
  'popup.status.downloadProgress': '{downloaded}/{total} files saved',
  'popup.status.progressComplete': '{progress}% complete',
  'popup.status.readyToCapture': 'Ready',
  'popup.status.savingCapture': 'Saving your capture...'
} as const satisfies Record<string, string>;
